%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/huziqi/database/RGB-D/rgbd_dataset_freiburg1_xyz/

# camera intrinsics
# TUM
#camera.fx: 535.4
#camera.fy: 539.2
#camera.cx: 320.1
#camera.cy: 247.6

# KITTI
camera.fx: 718.856
camera.fy: 718.856
camera.cx: 607.1928
camera.cy: 185.2157

camera.depth_scale: 5000

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 10
min_inliers: 30
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1
